name: Ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install just
        uses: extractions/setup-just@v1
      - name: ci
        run: just ci
